#!/bin/sh

dirname=`dirname $(readlink -f $0)`

tmp="${dirname#?}"

if [ "${dirname%$tmp}" != "/" ]; then
dirname=$PWD/$dirname
fi

LD_LIBRARY_PATH="$dirname/lib"
export LD_LIBRARY_PATH

export QTDIR=""
export QT_PLUGIN_PATH=""
export KDEDIRS=""
export KDEDIR=""

"$dirname/bin/paperpile" $*
