--- #YAML:1.0
name:                Bibutils
version:             0.01
abstract:            Perl wrapper for the Bibutils library
license:             ~
author:              
    - Stefan Washietl <wash@>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
