#!/usr/bin/perl

# Wrapper script to ensure the scripts/run.pl is called with the right perl executable

use Config;

my $platform='';
my $arch_string=$Config{archname};

if ( $arch_string =~ /linux/i ) {
  $platform = ($arch_string =~ /64/) ? 'linux64' : 'linux32';
}

if ( $arch_string =~ /(darwin|osx)/i ) {
  $platform = 'osx';
}

if ( $arch_string =~ /(win32|msys)/i ) {
  $platform = 'win32';
}


$ENV{PERL5LIB}=undef;
$ENV{PLATFORM}=$platform;

exec("../perl5/$platform/bin/paperperl scripts/run.pl " . join(" ",@ARGV));

